# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/unionproto.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'proto/unionproto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/unionproto.proto\"A\n\x08MsgType1\x12\r\n\x05value\x18\x01 \x02(\x05\x12&\n\x06\x61\x63\x63\x65ss\x18\x02 \x01(\x0e\x32\x0b.AccessMode:\tREAD_ONLY\"A\n\x08MsgType2\x12\r\n\x05value\x18\x01 \x02(\x08\x12&\n\x06\x61\x63\x63\x65ss\x18\x02 \x01(\x0e\x32\x0b.AccessMode:\tREAD_ONLY\"R\n\x08MsgType3\x12\x0e\n\x06value1\x18\x01 \x02(\x05\x12\x0e\n\x06value2\x18\x02 \x02(\x05\x12&\n\x06\x61\x63\x63\x65ss\x18\x03 \x01(\x0e\x32\x0b.AccessMode:\tREAD_ONLY\"Y\n\x0cUnionMessage\x12\x17\n\x04msg1\x18\x01 \x01(\x0b\x32\t.MsgType1\x12\x17\n\x04msg2\x18\x02 \x01(\x0b\x32\t.MsgType2\x12\x17\n\x04msg3\x18\x03 \x01(\x0b\x32\t.MsgType3*+\n\nAccessMode\x12\r\n\tREAD_ONLY\x10\x00\x12\x0e\n\nREAD_WRITE\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.unionproto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCESSMODE']._serialized_start=335
  _globals['_ACCESSMODE']._serialized_end=378
  _globals['_MSGTYPE1']._serialized_start=26
  _globals['_MSGTYPE1']._serialized_end=91
  _globals['_MSGTYPE2']._serialized_start=93
  _globals['_MSGTYPE2']._serialized_end=158
  _globals['_MSGTYPE3']._serialized_start=160
  _globals['_MSGTYPE3']._serialized_end=242
  _globals['_UNIONMESSAGE']._serialized_start=244
  _globals['_UNIONMESSAGE']._serialized_end=333
# @@protoc_insertion_point(module_scope)
