/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "proto/unionproto.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MsgType1, MsgType1, AUTO)


PB_BIND(MsgType2, MsgType2, AUTO)


PB_BIND(MsgType3, MsgType3, AUTO)


PB_BIND(UnionMessage, UnionMessage, AUTO)





